### ISSUE TITLE
Nordnet login broken

### ISSUE THREAD

**Issue by ribbefjord** [liato/android-bankdroid#104]
Nordnet has changed their login form to encrypt the password value by JavaScript before making the login POST request.

POST data now looks like this example:

7035cf0a5fd02f6d98ad52b4c1eb4491:username
0af1018c7cca9e346e9fa15a9b91316c:HsnALiW9nozGM9EeINvNKhg7OuQ6jIj4mC3N5uiCkpeK cqVXjNHU46i3DgzgnE14xXNDtyER0zdvArzkshk7Q==

This looks as not to be handled by Bankdroid and hence, login to Nordnet is now broken.

**Comment by dizmoduck** [comment]
Just opdate to 1.9.8.0-RC1 on Kit Kat 4.4.2
Clean the cache

Same isue as before
NordNet account don't work
No Account found

**Comment by goober** [comment]
Thanks for you report. We will take a look at it as soon as possible.

**Comment by l-g** [comment]
I still have this issue with the current version of Bankdroid.

**Comment by frebo72** [comment]
Works fine for me.

And Rikslunchen is back up again to :+1:
