### ISSUE TITLE
Swedbank Business

### ISSUE THREAD

**Issue by ghost** [liato/android-bankdroid#122]
Hi!

When you have a "Bättre affärer" account at Swedbank you have two views. One for personal accounts and one for your business accounts.

When I log in I get to click on the respective link for personal or business accounts, depending on which ones I'd like to see. I think Bankdroid is great! I would love if I could see my business accounts as well.

I'd like to help in any way I can. I can save HTML for the log in screen and some more screens if that would help. I'm a programmer myself, so if it's fairly easy to get into the source and contribute I could provide a patch, in this case I would need a few points to get me started.

**Comment by goober** [comment]
Closing this issue and further discussion should be kept in #316
