### ISSUE TITLE
Separate bank imports into own library

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#163]
I suggest that everything that is associated with the actual bank import is refactored out into an own library.
If it is possible to only include non-android specific code into the library it can be used by other java or JVM-based projects as well. 

The positive effect with this change is that the community which provides fixes will hopefully grow.

At the same time I suggest that the repository for bankdroid and the included library are moved into a separate "organization" account here at github.

I just want to start a discussion around this and see what you, and anybody else, think about this?

**Comment by aioobe** [comment]
Is there any progress (or planned effort) on moving in this direction? The Bankdroid code is awesome and it's such a shame I can't use bank import classes without providing for instance an android.content.Context.

**Comment by goober** [comment]
@aioobe Unfortunately, the work on this task is currently put on hold. There are some initial ground work done in #596 which is needed for separating the fetching into a pure java implementation. If you feel that you are interested in helping out with this, please let me know and we could discuss the details further. I do not have a lot of time to spend on this project at the moment, so all additional help is highly appreciated.
