### ISSUE TITLE
Add www.cellip.com prepay telephone, SIP account.

### ISSUE THREAD

**Issue by G-M** [liato/android-bankdroid#230]
please add https://www.cellip.com/
to be able to view account balance for the telephone pre pay.
its simple https pages.

amount found, like
Saldo: ###.#
and there is call lists and more to fill 2nd part pages with, and possibility to add several prepay numbers in one acount.
i can post html contents to get information from.
dont want to post all now as quite big, and its several files of html to pull data from.
also needs to remove "secret stuff before posting".

if want to try to add contact me for more stuff and to try it so works.
cheers.

**Comment by goober** [comment]
Closed due to missing information.
