### ISSUE TITLE
Inaktivera automatiskt uppdatering när man inte är i Sverige. 

### ISSUE THREAD

**Issue by MarijoEdlund** [liato/android-bankdroid#247]
Jag glömde att stänga av appen senast jag var utomlands och jobbade inte kul,
Jag skulle önska att appen inte uppdaterade konton automatiskt när man är utomlands.

**Comment by fredrike** [comment]
Related to #48, I guess that with the built in Sync service this should be configurable globally on the device.

**Comment by goober** [comment]
Yes, that is true. I will close this and further discussion should be done in #48

**Comment by fredrike** [comment]
Just had a look at the code and in (AutoRefreshService.java)[https://github.com/liato/android-bankdroid/blob/019fba9031b0cd8081a1c0eb44eb8c5360ebf3ce/app/src/main/java/com/liato/bankdroid/appwidget/AutoRefreshService.java#L83] there is the possibility to test for `cm.getActiveNetworkInfo().isRoaming()` i.e., it should be fairly easy to test if the user isRoaming and then just skip that update..
