### ISSUE TITLE
SEB not working

### ISSUE THREAD

**Issue by mikjo243** [liato/android-bankdroid#303]
Get same error message as for OKQ8 at the moment. 

Also I wonder what will happen when SEB now stops using a password for logins. BankID will be needed.

**Comment by goober** [comment]
Closed as `wontfix` because SEB now requires BankId

**Comment by Raboo** [comment]
Hey,
Perhaps you guys don't realize that you still can login to SEB without BankID.
go to https://m.seb.se/
To get the signature use the digipass to extract the signature(it is static).
So no need for BankID yet...
