### ISSUE TITLE
Avanza Bank doesn't show everything

### ISSUE THREAD

**Issue by ghost** [liato/android-bankdroid#336]
I have both stocks (Aktier) and funds (Fonder) in my account on Avanza but it only shows my stocks. Before I bought the stocks It showed the funds. So there is something strange going on.

**Comment by fredrike** [comment]
@larschanders I've played around a bit more with the avanza account, what do you think about this. Showing all different types of sub-accounts from the main view.

The account type is "OTHER" so the sub-accounts does not add up to the Bank total.

![bankdroid](https://cloud.githubusercontent.com/assets/676999/5991740/97ae389e-aa02-11e4-8736-ab349746c184.png)

The type SEK is the "Saldo" or "Tillgängligt för köp".

What do you think?
