### ISSUE TITLE
Can't add swedbank account 

### ISSUE THREAD

**Issue by dnilss** [liato/android-bankdroid#381]
Since the implantation of swedbank API I have been unable to use my swedbank account. I have updated to the latest version (1.9.7.3) and have tried to re-install the app. 
When I try to add it now it returns the fault "Kunde inte skapa konto" "HTTP/1.1 404 Not Found".
I have tried to change my password on swedbank but it still will not work.
![bankdroid](https://cloud.githubusercontent.com/assets/9918950/5159217/832d3280-735c-11e4-911a-aa7a0f45e890.jpg)

**Comment by goober** [comment]
I will try to fix this issue until the next release.
@dnilss Do you still have problems with your Swedbank account?

**Comment by dnilss** [comment]
@goober Yes, I tried adding my swedbank account after the last release but with the same result unfortunately.

**Comment by goober** [comment]
Can you get the transaction history for your corporate credit card in the official application?

**Comment by goober** [comment]
I will build a new release candidate today with the change above included. This will at least make you add your Swedbank account, but there will not be any transaction history for your corporate credit card.

**Comment by goober** [comment]
If you are not part of the Beta community I recommend you to join to get faster updates.
[Bankdroid Beta] (https://play.google.com/apps/testing/com.liato.bankdroid)

**Comment by dnilss** [comment]
@goober I can't see transactions in the official application no. Just what the balance for the card is

**Comment by goober** [comment]
Great. Then your problem should have been fixed with the latest release. I will try to push it to production on Sunday.

**Comment by dnilss** [comment]
@goober I downloaded the Beta version and now it works just the way it's suppose to :)

Thank you for the upgrade :)
