### ISSUE TITLE
IcaBanken certificate out-of-date

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#384]

**Comment by O5ten** [comment]
Any updates on this? Seems like a fairly easy thing to resolve, but obviously protected by proguard so liato has to do it.

**Comment by Scootch** [comment]
I would like to get this fixed as well!

**Comment by liato** [comment]
Sorry for the delay. Fixed by 5dac6464cd061076dbd9a516e98fad2f648d82c8.

**Comment by eddie-dunn** [comment]
Hi, how long until this update gets pushed to Google play?
