### ISSUE TITLE
Show swedbank "SKYDDAT BELOPP"

### ISSUE THREAD

**Issue by glance-** [liato/android-bankdroid#388]
Its awesome that you get a notifier when money is reserved, but it would be great if those reservations or "SKYDDAT BELOPP" where to show up in the transaction history as they did before switching to the api based implementation.

**Comment by goober** [comment]
I just found that all reserved transations are added to the bottom of the list. Could you confirm that your "SKYDDAT BELOPP" transactions are included, but are placed at the bottom?

**Comment by glance-** [comment]
Yepp. I can confirm that "SKYDDAT BELOPP" are at the bottom of the list now, but with the correct date.

Maybe the data needs to be sorted by date to be less confusing?
