### ISSUE TITLE
Certificate issue with American Express

### ISSUE THREAD

**Issue by kaunio** [liato/android-bankdroid#406]
I get an error when trying to add an American Express account

"Could not create account

Server certificate not trusted for host: global.americanexpress.com"

**Comment by fredrike** [comment]
Fixed by this 81ae6c4060368277f755227195e1227cfaaf29c9?

**Comment by goober** [comment]
@fredrike correct. 
@kaunio Should be available for you in a couple of hours if you are part of the Beta program or in the end of the week if you use the production version.
