### ISSUE TITLE
Account names with numbers do not work for Nordea

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#422]
Accounts that has custom names does not work.
A set of the following names gives an "No Accounts Found" error

Example naming structure
P 800224-5678
G 1234 12 12345
SP 4321 12 54321
SG 4312 21 12354

All account are found if the custom names are removed.

**Comment by fredrike** [comment]
In particular, account names with numbers are not supported..

I guess the error is here: bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/nordea/Nordea.java#L166

**Comment by fredrike** [comment]
Or rather this pattern is not complete if an account name have a starting number.

```java
    private Pattern reAccountOption = Pattern.compile("<option[^>]+value=\"([\\d]+)\"[^>]*>.*?([*\\d]+)", Pattern.CASE_INSENSITIVE | Pattern.DOTALL);```
