### ISSUE TITLE
Make crashlytics optional

### ISSUE THREAD

**Issue by krt16s** [liato/android-bankdroid#450]
Crashlytics is non-free software. Is there a easy way to build without it?

**Comment by goober** [comment]
Thanks for your comment. We tried to make it optional from the beginning but had some issues. I will take a look at this as soon as we start the development of the next minor version. In the mean time you can just comment out [app/build.gradle#L11] (https://github.com/liato/android-bankdroid/blob/76550c602d5877fed8877c60f5fe356bc10d6d80/app/build.gradle#L11) and it will compile without crashlytics.

**Comment by goober** [comment]
We are of course accepting a pull request if you have a way of disabling it in another way.
