### ISSUE TITLE
Check internet connectivity before trying to update a bank.

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#466]
To improve the error handling and the user experience we should check the internet connectivity before we are trying to connect to a bank.

See http://stackoverflow.com/a/27312494/738903 for a nice implementation.

**Comment by fredrike** [comment]
And what if the connection is lost during update (between two `urllib.open`)?

I think it's better to handle `UnknownHostException` and `ConnectException`. But then it's good to know if it is a bank connectivity issue or a network issue.

**Comment by goober** [comment]
Good point. 

We do already have the `android.permission.ACCESS_NETWORK_STATE` permission so if we check if there is a network available at all before we do an update and then handle `UnknownHostException` and `ConnectException` by doing an extra ping to a known host when they have been thrown.

**Comment by fredrike** [comment]
Great!

**Comment by goober** [comment]
My suggestion is to re-throw all `IOException`s from the bank implementations and handle it one level up by checking if there is a network connection and if it is also send a `HEAD` request to `google.se`. If the ping succeeds it could be a problem with the implementation. Otherwise there is most probably a missing internet connection.

**Comment by fredrike** [comment]
This is sufficient: http://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html#isReachable%28int%29

We don't need to know the whole `HEAD` part, just verify that the net is up.

**Comment by fredrike** [comment]
Do we need to re-throw `IOException` can't we just ignore in `Bank.login()` and `Bank.update()` and let the method throw the `IOException`s?

**Comment by goober** [comment]
@fredrike Good point about just ignore the Exception and catch it later. I will do that.
Regarding the [InetAddress#isReachable](http://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html#isReachable%28int%29), it seems like it [does not work well on Android](
http://stackoverflow.com/a/2935468/738903) and that is why I will go with the `HEAD` approach.
