### ISSUE TITLE
Skandiabanken broken

### ISSUE THREAD

**Issue by denizdogan** [liato/android-bankdroid#491]
My Skandiabanken account stopped working today. I removed it and tried adding it again, but I get the error "Could not create account" with the message "Oväntat svarsformat No value for id".

**Comment by goober** [comment]
It seems that they have removed the possibility to login without BankId. as @fredrike reference to.

**Comment by goober** [comment]
I will close this due to the requirement of BankId. For further discussion regarding support of banks with BankId see #492
