### ISSUE TITLE
Swedbank corporate profile is broken

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#513]
`GET engagement/overview` returns `401 Unauthorized` when using the Swedbank Corporate application key.

Need to investigate if we can use `profile/{profileId}` instead of `profile/private/{bankId}` for both private and corporate profiles. And verify the authentication flow.

**Comment by alesch** [comment]
Where in the project can I find the Swedbank related code?

**Comment by goober** [comment]
Swedbank now requires BankID for logging in. Closing this issue due to this.
