### ISSUE TITLE
Skodakortet not working 

### ISSUE THREAD

**Issue by mikjo243** [liato/android-bankdroid#525]
Server certificate not trusted for host:
partner.ikanobank.se

**Comment by goober** [comment]
Thanks for your report. It has been fixed by #521 and will be deployed to Play Store during the weekend.

**Comment by mikjo243** [comment]
Thanks.

**Comment by mikjo243** [comment]
Thanks!

**Comment by goober** [comment]
@mikjo243 Did Skodakortet work as expected before you got this error?

**Comment by mikjo243** [comment]
I think so yes. At least two weeks ago.
