### ISSUE TITLE
Forex slutar uppdatera efter ett tag

### ISSUE THREAD

**Issue by frinnst** [liato/android-bankdroid#559]
Ny forexkund så har inte kunnat testa äldre versioner. 

då o då slutar forex att fungera. Rött utropstecken.

Öppnar man www så ser man detta:
"Web page not available
The Web page at
what://is/Logon/logon/step1;jsessionid=<sträng> could not be loaded as:
net::ERR_UNKNOWN_URL_SCHEME"

Tar jag bort kontot och lägger till det igen så fungerar det i 0.5-3dagar igen. reboot hjälper inte.

**Comment by fredrike** [comment]
Verkar som det är någon caching som ställer till det. Dock har inte bankDroid support för cashing, så väldigt märkligt.

Kan du prova att välja edit och spara nästa gång forex inte fungerar, bara för att se om det fungerar bättre då.

**Comment by frinnst** [comment]
Ja, efter en enkel edit så började det fungera igen

**Comment by frinnst** [comment]
Kanske ska tillägga att det endast fungerar ett tag efter en edit. Fortfarande samma problem
