### ISSUE TITLE
Swedbank broken (password authentication no longer supported)

### ISSUE THREAD

**Issue by auno** [liato/android-bankdroid#566]
(This should come as no surprise for anyone involved, but I couldn't find an existing issue documenting this).

Swedbank support is now completely broken as password authentication ("personlig kod") was disabled for third party applications on 2015-09-03 after the following notice:

> Hej,
> 
> I linje med Datainspektionens rekommendation kommer banken under 2015 att ta bort personlig kod som inloggningsmetod till internet-och mobilbanken.
> Här får du information om hur det påverkar om du använder en eller flera s.k. tredjepartstjänster, t.ex. Tink, Mitt saldo, Bankdroid eller Bankhubben.
> 
> Personlig kod tas bort till tredjepartstjänster
> Efter 3 september 2015 kommer det inte längre vara möjligt att logga in via tredjepartstjänster med den personliga koden. Använder du en tredjepartstjänst kontaktar du det företaget för att få information om hur du gör för att fortsätta använda tjänsten. Tänk på att dina inloggningsuppgifter är personliga och har till syfte att ge dig tillgång till dina konton och övriga tjänster som du använder.
> 
> Har du frågor är du välkommen att kontakta vår support för internet- och mobiltjänster på 0771 - 97 75 12. Öppet alla dagar 07-23 med undantag för storhelger.
> 
> Med vänlig hälsning,
> Swedbank och Sparbankerna

**Comment by fredrike** [comment]
Related to #526.
