### ISSUE TITLE
Unable to add banks without a password field

### ISSUE THREAD

**Issue by jonasgroth** [liato/android-bankdroid#579]
It's not possible to add new "banks" that only requires a username. For example Chalmrest and Bitcoin only uses a card number or wallet address. When I try to adding one them nothing happens! If I change:
"super.INPUT_HIDDEN_PASSWORD = true;" to false and write something in the password field it works.

I think the problem is in https://github.com/liato/android-bankdroid/blob/d36af84b78a28b40516c07f205710e8dc6c4025d/app/src/main/java/com/liato/bankdroid/BankEditActivity.java#L223-L237.

**Comment by goober** [comment]
Thank you

It is actually when the field is created that we are currently assuming that the password field is required.
This should be changed so it should only be required if it is not hidden.
 
https://github.com/liato/android-bankdroid/blob/d36af84b78a28b40516c07f205710e8dc6c4025d/bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/LegacyProviderConfiguration.java#L44-L50
