### ISSUE TITLE
Länsförsäkring account creation

### ISSUE THREAD

**Issue by peppot** [liato/android-bankdroid#580]
Error when trying to add Länsförsäkringar account
![pb220001](https://cloud.githubusercontent.com/assets/3662891/11324283/b9d23be2-912d-11e5-80c0-349125ae3805.JPG)

**Comment by donnex** [comment]
I'm having the exact same issue but for an existing account. I've been running Bankdroid for a very long time but the other day I noticed that it wasn't updating any more. When I tried a manual refresh I get the same message.

**Comment by jmbe** [comment]
+1

**Comment by hasise** [comment]
+1

**Comment by Paronfesken** [comment]
+1

**Comment by furumosse** [comment]
+1

**Comment by mogren** [comment]
Same here..

**Comment by lisros** [comment]
Is anyone working on this issue? I have the same problem, so does my husband.

**Comment by kruka** [comment]
Kan inte uppdatera konton.

**Comment by peppot** [comment]
Possible to sponsor this issue?

**Comment by donnex** [comment]
I would love to sponsor this issue as well, if that's even possible :) Really missing my Bankdroid :/

**Comment by glance-** [comment]
The response format for the api have changed, and for a GET against https://mobil.lansforsakringar.se/appoutlet/security/client it doesn't return valid json anylonger, it returns something that looks like:
{{
!!se.lf.mobile.rest.security.model.Challenge {number: 305986295, numberPair: 1c4d1ee0d1a0e41a92394cd16b43d7de}
}}

Dunno what sort of "protocol" that is.

**Comment by goober** [comment]
Fixed by 1d152a2cd7be328f5501c38b845d23f8d611215e

**Comment by hasise** [comment]
Thanks for the correction, a very appreciated "Christmas gift"
