### ISSUE TITLE
allow "panic button" apps to lock Bankdroid

### ISSUE THREAD

**Issue by eighthave** [liato/android-bankdroid#593]
We (Guardian Project) have been developing "panic button" features in our apps for years, and now we are working to make a more flexible and open ecosystem of apps that can both trigger other apps, or respond to triggers. Since banking should be as private as possible, Bankdroid is a natural panic responder app, for example, by having Bankdroid lock when the "Pattern Lock" is enabled and a panic message is received. This setup allows for easy configuration of a single trigger action which can then trigger multiple apps.

You can see an example of this user experience in this video:
https://www.youtube.com/watch?v=mS1gstS6YS8

It is simple to implement, here are some examples of other apps:
* https://github.com/SMSSecure/SMSSecure/pull/290
* https://github.com/theScrabi/NewPipe/pull/133
* https://github.com/bpellin/keepassdroid/pull/72

The first panic button app that sends this kind of trigger is called Ripple, and it is available here:
https://github.com/guardianproject/ripple
https://play.google.com/store/apps/details?id=info.guardianproject.ripple

I'm adding support to this app right now:
https://panicbutton.io/
https://play.google.com/store/apps/details?id=org.iilab.pb

More info on the panic kit work here:
https://dev.guardianproject.info/projects/panic/wiki

**Comment by goober** [comment]
Thanks for the suggestion. This is currently out of scoop for the application. Closing for now.
