### ISSUE TITLE
Broken bank: OKQ8

### ISSUE THREAD

**Issue by mikjo243** [liato/android-bankdroid#597]
Since a week or so OKQ8 bank doesn't work. It stopped updating. I removed it and now I can't add it. It says "no account found". 

Maybe related: I had an old bookmark to their log in page. That log in now gives an error. If I instead go to their main page and choose log in,  I'm sent to a new login page which works.

**Comment by mikjo243** [comment]
Seriously? Nothing?

**Comment by fredrike** [comment]
Seriously, yes. 

What is the new url? Does the new page look like the old one?

**Comment by mikjo243** [comment]
https://nettbank.edb.com/payment/index.jsp?n_bank=0066

They look similar. But it's a new url. I had the old one as bookmark. But could not log in through it. You have to use the new one (above).
