### ISSUE TITLE
ICA Banken crashes when adding new account

### ISSUE THREAD

**Issue by vlopezj** [liato/android-bankdroid#601]
How to reproduce:

1. Add a new ICA Banken account with our without a custom name.

Expected behaviour:

A new account is added, and the saldo is shown.

Actual behaviour:

The message "Loggar in" is shown. The app crashes. The account has not been added when the app is restarted.

Here's the log:

[2016-03-05-15-13-52.txt](https://github.com/liato/android-bankdroid/files/159870/2016-03-05-15-13-52.txt)

I'm running version 1.9.10.4 on Android 4.4.4, Cyanogen Mod 11-20141115-SNAPSHOT-M12-d802 on an LG G2.

**Comment by goober** [comment]
Resolved by #620
