### ISSUE TITLE
Should the two DataRetrieverTask classes be merged?

### ISSUE THREAD

**Issue by walles** [liato/android-bankdroid#607]
This is more of a question than an actual issue, but here goes:

There are two `DataRetrieverTask` classes:
* One in `com/liato/bankdroid/appwidget/AutoRefreshService.java`
* One in `com/liato/bankdroid/DataRetrieverTask.java`

The first one is the one used when accounts are auto updated. It sometimes forgets to update the widget.

The second one looks quite similar but does seem to update the widget all the time.

Why two? Should they be merged? Can fish drown?

  Regards /Johan

**Comment by goober** [comment]
I think @liato can answert this question, since he is the author of that particular part. However, from my point of view there is no reason to have them separated.

**Comment by goober** [comment]
and of course pull requests on this one is approved :)

**Comment by walles** [comment]
Nah, I did #608 instead. Never mind.
