### ISSUE TITLE
Disabled banks UI updates

### ISSUE THREAD

**Issue by walles** [liato/android-bankdroid#610]
I just had my bank disabled because of a failed update and it was really un-obvious, both what was wrong and what I could do about it.

My plan A is to provide PRs for these things, but who knows how things go?

- [x] The "disabled" marker in the 2x1 widget is almost entirely outside of the widget on my phone. I suggest removing it entirely and overstriking the balance numbers instead if the bank has been disabled and isn't updating any more.
- [x] Clicking the widget when my account is disabled shows me a list which says nothing about anything being disabled. This view should say in clear text that the bank is disabled and what I could do about it.
- [x] Clicking the bank in that list takes me to another view where the same bank now has a red marker. This view should say in clear text that the bank is disabled and what I could do about it.
- [x] Clicking the disabled bank and clicking the `Refresh` icon has no effect. This should retry updating the bank and re-enabling it if it worked.

**Comment by goober** [comment]
There are also an older issue (#244) that is related to this one. Just adding a reference for documentation reasons.

**Comment by fredrike** [comment]
@walles, you should really join our slack channel https://bankdroid.herokuapp.com/

**Comment by goober** [comment]
Fixed by #655
