### ISSUE TITLE
Support for banks with one-time passwords

### ISSUE THREAD

**Issue by mridang** [liato/android-bankdroid#93]
Some banks such as Nordea Finland use one-time passwords for extra security unlike Nordea Sweden which uses the SSN and password. It would be nice to add support these one-time passwords. One way to do this would be to provide notifications to user which upon being clicked, displays a password prompt. The user then types in the one-time password and the account balance and transactions are then updated. This would make the app more accessible to more developers who then support other Nordic banks with one-time passwords.

Another way would be to allow the user to store all the one-time passwords in the system.

**Comment by goober** [comment]
Closed as `wontfix` because it would be unpractical for en users.
